[package]
name = "pico-data-logger"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"
cyw43 = { version = "0.7", features = ["log"] }
cyw43-pio = "0.10"

embassy-executor = "0.10"
embassy-time = "0.5"
embassy-usb = "0.6"
embassy-usb-logger = "0.6"
embassy-net = { version = "0.9", features = ["dhcpv4", "dns", "tcp", "udp"] }
log = "0.4"
static_cell = "2"
panic-halt = "1.0"

[dependencies.embassy-rp]
version = "0.10"
features = [
    "rp235xa",
    "time-driver",
    "critical-section-impl",
    "executor-thread",
]

[profile.release]
codegen-units = 1
debug = 2
lto = "fat"
opt-level = "s"
